### ISSUE TITLE
Pip install adds a tests/test_kim_property directory under dist-packages

### ISSUE THREAD

**Issue by ilia-nikiforov-umn** [openkim/kim-property#16]
This seems unnecessary. It is also happening in kim-edn and kim-convergence

**Comment by yafshar** [comment]
@ilia-nikiforov-umn, is there a reason for this suggestion? Many packages that try to exclude tests suffer from space-time or compile-time issues. We use tests as part of the distribution for extra testing, and our test is small enough not to cause any issues.

**Comment by ilia-nikiforov-umn** [comment]
Nope, if it's known and not an issue, then no problem, sorry!

**Comment by yafshar** [comment]
@ilia-nikiforov-umn, I will probably exclude the tests from the distribution after I update the packages. I was curious if you have found any issues.

**Comment by ilia-nikiforov-umn** [comment]
No functional issues -- my only concern that it seemed not neat, and that
Dan has worked very hard to minimize the size of the KDP, but there are
tests from 3 different packages left over. As you say, though, the space
they take is tiny.

**Comment by yafshar** [comment]
I have started to upgrade the installation, actions and packaging and removing tests is easy. I will have that in the next release.

**Comment by ilia-nikiforov-umn** [comment]
Great, thank you! I temporarily made a branch called "spoof-version" to allow for local editable installations without complaints, which we will need for the hackathon we are starting on Monday. Otherwise, I will not touch the other branches unless an update of "openkim-properties" is necessary.
